spectacular: 0.1
catalogues:
  testCatalogue1:
    title: "Test Catalogue 1"
    description: "Specifications for all the interfaces across system X."
    interfaces:
      interface1:
        specFile:
          filePath: "specs/example-template.yaml"
      interface2:
        specFile:
          filePath: "specs/error-example.yaml"
      interface3:
        specFile:
          filePath: "specs/example-spec.yaml"
          repo: "specmore/specs-test2"
      interface4:
        specFile:
          filePath: "specs/example-template.yaml"
          repo: "specmore/specs-test-no-access"
